---
apiVersion: v1
kind: Service
metadata:
  name: spy
  labels:
    app: spy
spec:
  ports:
    - port: 7073
      name: spyrpc
      protocol: TCP
    - port: 6060
      name: status
      protocol: TCP
  clusterIP: None
  selector:
    app: spy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spy
spec:
  selector:
    matchLabels:
      app: spy
  serviceName: spy
  replicas: 1
  template:
    metadata:
      labels:
        app: spy
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: spy
          image: guardiand-image
          command:
            - /guardiand
            - spy
            - --nodeKey
            - /tmp/node.key
            - --spyRPC
            - "[::]:7073"
            - --network
            - /wormhole/testnet/2/1
            # Hardcoded testnet bootstrap from relayer/spy_relayer/README.md
            - --bootstrap
            - /dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i
#            - --logLevel=debug
          ports:
            - containerPort: 7073
              name: spyrpc
              protocol: TCP
            - containerPort: 6060
              name: status
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 6060
              path: /metrics
